---
title: "Australian Election Study, 2019"
author: 
date: 
output:
  xaringan::moon_reader:
    css: ["default", "libs/mjc-css/mjc-theme.css", "libs/mjc-css/mjc-fonts.css"]
    lib_dir: libs
---
  
```{r setup, include=FALSE}

knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, dpi = 300, fig.height = 3.5)

library(knitr)

source("aes_19.R")

```

## Importance of issues

```{r }
p_aes_d1$taxation

```

___

## Importance of issues

```{r }
p_aes_d1$`management of the economy`

```

___

## Importance of issues

```{r }
p_aes_d1$immigration

```

___

## Importance of issues

```{r }
p_aes_d1$education

```

___


## Importance of issues

```{r }
p_aes_d1$`the environment`

```

___


## Importance of issues

```{r }
p_aes_d1$`government debt`

```

___


## Importance of issues

```{r }
p_aes_d1$`health and medicare`

```

___

## Importance of issues

```{r }
p_aes_d1$`refugees and asylum seekers`

```

___

## Importance of issues

```{r }
p_aes_d1$`global warming`

```

___


## Importance of issues

```{r }
p_aes_d1$superannuation

```


